language: c
sudo: false
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libx264-dev
      - libpostproc-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
      - libasound2-dev
      - libsndio-dev
      - libsdl2-dev
      - libxv-dev
      - liblzma-dev
env:
    - HOST=linux
    - HOST=windows
    - HOST=osx
matrix:
  exclude:
    - os: osx
      env: HOST=linux
    - os: osx
      env: HOST=windows
    - os: linux
      env: HOST=osx
before_install:
  - if [ "$HOST" == "osx" ]; then brew update; fi
install:
  - if [ "$HOST" == "osx" ]; then brew install sdl2; fi
script:
  - echo "RUNNING PWD"
  - pwd
  - echo $TRAVIS_BUILD_DIR
  - wget -O ffmpeg.zip https://github.com/ashotkhachatryan/FFmpeg/releases/download/v4.3/$HOST.zip
  - mkdir ffmpeg; unzip -d ffmpeg/ ffmpeg.zip 
  - ls $TRAVIS_BUILD_DIR/ffmpeg/$HOST
  - mkdir build; cd build;
  - if [ "$HOST" == "linux" ]; then cmake -DLINUX=1 -DLIBDIR=$TRAVIS_BUILD_DIR/ffmpeg/$HOST/lib -DINCDIR=$TRAVIS_BUILD_DIR/ffmpeg/$HOST/include ..; fi
  - if [ "$HOST" == "windows" ]; then cmake -DWINDOWS=1 -DLIBDIR=$TRAVIS_BUILD_DIR/ffmpeg/$HOST/lib -DINCDIR=$TRAVIS_BUILD_DIR/ffmpeg/$HOST/include ..; fi
  - if [ "$HOST" == "osx" ]; then cmake -DMACOS=1 -DLIBDIR=$TRAVIS_BUILD_DIR/ffmpeg/$HOST/lib -DINCDIR=$TRAVIS_BUILD_DIR/ffmpeg/$HOST/include ..; fi
  - make
before_deploy:
  - echo "PRINTING USEFULL INFORMATION"
  - pwd
  - zip -r $HOST.zip main*
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "ebQc3XgyaC4dnXks/QXgOegpUk+vUf27VI9j1Ks+SoMgjv0jcrBRIB3x5NGZvvMktdqSCP8K3To8l7fxMbTHyqpnxnyr0Ew6eeo578FdEqwk4zr2vUJfnfUmIK5i/AkM7o/Cfr8fVhgSYoQJr07DhjCqFabbYQVvSqcD/jRGo3z9tKlzZbLFNxSSJHS8bQ6KZrrbB4XetXdj6YlEXZ7wATl1uDAHBZeb6ZG/XPg+5OBZ+GscYJvtADYhlf6TUw7GchdCxXIfWsP40XddjoZi/ZbFGpG6tFqQlK9lKbmEvadyAYnWOrhqnqh1crbjq1J+WgGB3GZB9TypSwLfShI5E5evFdabmDlz3ejWLORHgOcN7upmzJuYhP0uGgbDDuM7cfKfvTQihnLylfaIRUnV5OdCulYdWmO0E1lXOWqb1gS90CzsTfK+2H7KcfmRl6vEhkaqTWEaQJ/9cvTNWzt+HijOp46B8mitrt969wwHK2EhpBeyy+qjlsgqcBGbOWpxfUzIfSlLbgYDNKqBOElL7mwakgWyVQMqloI6d6F+bCNZ/x2jlthOmeXY+8lxvJTXqKTJpIBndLCB8CepGoS2vIG5vQavP4bTzZlJxfNK4etU3LOw2dXIC0gh5zVpsL5BZ/u+O7Yo3DzEHijZ0orBZ9UviXDUf9sxN+w88gIz3Oo="
  file:
    - $HOST.zip
  on:
    repo: ashotkhachatryan/screenrecorder
    tags: true
    all_branches: true
